server:
    port: $PORT
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:test.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1
